management:
  endpoints:
    web:
      exposure:
        include: env,health,refresh,restart,info
  endpoint:
    restart:
      enabled: true
    refresh:
      enabled: true
spring:
  application:
    name: my-app

debug: true