management:
  endpoints:
    web:
      exposure:
        include: env,health,refresh,restart,info
  endpoint:
    restart:
      enabled: true
    refresh:
      enabled: true
spring:
  application:
    name: my-app
  cloud:
    kubernetes:
      config:
        fail-fast: true
      reload:
        enabled: true
        monitoring-secrets: true
        monitoring-config-maps: true
        strategy: refresh
        mode: event
      secrets:
        enabled: true
        name: my-local-secret
        namespace: spring-3-cloud-config


debug: true