apiVersion: v1
kind: Pod
metadata:
  name: spring-3-cloud-config
  labels:
    name: spring-3-cloud-config
spec:
 containers:
    - name: spring-3-cloud-config
      image: localhost:5000/spring-3-cloud-config:latest
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: file-config-my-app
      env:
        - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
          value: "true"
      volumeMounts:
        - name: the-gunslinger-secret
          mountPath: "/opt/application/secrets"
          readOnly: true
        - name: names-configmap
          mountPath: "/opt/application/configs"
 volumes:
   - name: the-gunslinger-secret
     secret:
       secretName: the-gunslinger-secret
   - name: names-configmap
     configMap:
       name: names-configmap

