apiVersion: v1
kind: Pod
metadata:
  name: spring-3-cloud-config
  labels:
    name: spring-3-cloud-config
spec:
 containers:
    - name: spring-3-cloud-config
      image: localhost:5000/spring-3-cloud-config:latest
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: names-configmap
      env:
        - name: SPRING_CLOUD_BOOTSTRAP_ENABLED
          value: "true"
 volumes:
   - name: first-volume
     configMap:
       name: my-app


