apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-3-cloud-config
  name: spring-3-cloud-config
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    name: spring-3-cloud-config
  type: NodePort